version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.29
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dws_healthcare
      MYSQL_USER: user
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - "3306"
    restart: always
    volumes:
      - ./mysql-5-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8183:80
volumes:
  db_data: